### ISSUE TITLE
compat=1.0.0 as option to package declaration

### ISSUE THREAD

**Issue by parnmatt** [JP-Ellis/tikz-feynman#10]
It would nice if the compat=1.0.0 could alternatively be used in the optional argument of the package declaration, *e.g.*, `\usepackage[compat=1.0.0]{tikz-feynman}`

Unless used else where, it would be logical to have `version` as an alias to `compat`

**Comment by JP-Ellis** [comment]
I hadn't thought of doing that, but it's definitely easy enough to do.  Thanks for the feedback :)

I'm not sure I want to have `version` as an alias for `compat` simply because I don't want people to think this loads a particular version of Ti*k*Z-Feynman.

**Comment by parnmatt** [comment]
That's a fair enough reason. 

And thank you for considering the idea. 
I do look forward to using this tool.
