### ISSUE TITLE
Spacing after [ prevents recognition of keys

### ISSUE THREAD

**Issue by martin-ueding** [JP-Ellis/tikz-feynman#15]
I like to split the optional arguments over multiple lines, like in this minimal (non-)working example:
```latex
\documentclass{scrartcl}
\usepackage{tikz-feynman}
\begin{document}

\feynmandiagram[
    horizontal=a to b,
]
{
    a -- b;
};

\end{document}
```

That works with most packages, here I get the following error:
```
! Package pgfkeys Error: I do not know the key '/tikz/ horizontal', to which yo
u passed 'a to b', and I am going to ignore it. Perhaps you misspelled it.
```

It is fixed then I use a percent sign right after the opening square bracket, like so:
```latex
\feynmandiagram[%
```

I am not sure why it works with other packages and not with this one, but I find it slightly irritating.

----

Thank you again for this great package, I made so many Feynman diagrams with it so far and I will continue to point out that `tikz-feynman` does not destroy the gray value of your page like `feynmp` does to everybody who does not believe that `tikz-feynman` is the way to go!

**Comment by JP-Ellis** [comment]
I'm glad you're liking Ti*k*Z-Feynman!

Now regarding this bug, it is indeed unintended behaviour.  Personally, I only like have arguments on a new line when the line would otherwise be unnecessarily long and since Ti*k*Z-Feynman doesn't usually need many arguments, I haven't encountered this so far.

I'll have a look at fixing this!

**Comment by JP-Ellis** [comment]
I have just pushed a commit to the [`develop`](https://github.com/JP-Ellis/tikz-feynman/tree/develop) branch which should fix this.  Hopefully it works for you too, otherwise, let me know if it still doesn't work.
