### ISSUE TITLE
out of the box first example of simple scattering diagram doesnt look right

### ISSUE THREAD

**Issue by rkunnawa** [JP-Ellis/tikz-feynman#29]
Hi, 
I just downloaded the classes and tried to draw the first example you have on the website and it came out looking quite weird? im writing it with ejpc 2column format. 
![test_feynman_diagram](https://cloud.githubusercontent.com/assets/5130634/15474985/ce7ff074-2107-11e6-884d-61664648077a.png)

Cheers
Raghav

**Comment by rkunnawa** [comment]
It looks like the problem is with the autoplacement. writing it like so

\begin{tikzpicture}
\begin{feynman}
\vertex (b);
\vertex [above left=of b] (a) {\(\mu^{-}\)};
\vertex [below left=of b] (f1) {\(\nu_{\mu}\)};
\vertex [right=of b] (c);
\vertex [above right=of c] (f2) {\(\overline \nu_{e}\)};
\vertex [below right=of c] (f3) {\(e^{-}\)};
\diagram* {
(a) -- [fermion] (b) -- [fermion] (f1),
(b) -- [boson, edge label'=\(W^{-}\)] (c),
(c) -- [anti fermion] (f2),
(c) -- [fermion] (f3),
};

works and produces something nice: 
![test_feynman_diagram2](https://cloud.githubusercontent.com/assets/5130634/15475273/84441740-2109-11e6-8f73-a6c4a70acc77.png)

**Comment by rkunnawa** [comment]
i cant for the life of me, get this code to display like code. sorry about that.

**Comment by JP-Ellis** [comment]
This issue is most likely because you are not compiling your document with LuaLaTeX.  Hopefully, there should be some warning messages in the log telling you about this though if you don't, please let me know.

**Comment by rkunnawa** [comment]
Hey, 
Yeah you are correct. Once i compiled it with LuaLaTex it worked fine! I think this is quite the useful package 👍 
Cheers
Raghav

**Comment by esel7353** [comment]
So tigz-feynman can only be used with LuaLaTex?

**Comment by JP-Ellis** [comment]
@esel7353 the basic features of Ti*k*Z-Feynman work with any compiler (pdfLaTeX, XeLaTeX, LuaLaTeX); however, the algorithms to automatically determine the placement of vertices is written in Lua and thus requires LuaLaTeX to work.  If you are not using LuaLaTeX, you'll have to use manually specify the position of the vertices (check the manual to see how that can be done).
