### ISSUE TITLE
An equivalent to \fmffreeze?

### ISSUE THREAD

**Issue by Lukelippstreu** [JP-Ellis/tikz-feynman#38]
I am attempting to draw the following diagram
![collinear radiation](https://cloud.githubusercontent.com/assets/26307980/23762549/ed3b3ed4-04fe-11e7-90de-78c2c3caccc8.png)

The difficulty I am having is in keeping the electron propagator straight. Using \feynmp this is easily achieved by using \fmffreeze prior to attaching external photon legs. Is there any way to achieve this using tikzfeynman?

**Comment by JP-Ellis** [comment]
The question is now answered on the TeX StackExchange at:

> [An equivalent to \fmffreeze in TikZ-Feynman?](http://tex.stackexchange.com/q/358195/26980)
