### ISSUE TITLE
Opacity not working sometimes

### ISSUE THREAD

**Issue by F-Feng** [JP-Ellis/tikz-feynman#39]
Hi sir, thanks very much for the great package.
I got a problem about the `opacity` when using Ti*k*Z-Feynman package, 

for example

```latex
\feynmandiagram{
v1  --[double distance=1.5pt,edge label=$n$]  e4[particle=$n$],
v1  --[double distance=1.5pt,edge label=$l$]  e2[particle=$l$],
e1  --[opacity=0]  v1,
};
```

the line connecting vertex `e1` and `v1` should not be visible, but the output looks like this one:
![tmp](https://cloud.githubusercontent.com/assets/8832209/25730806/c4290bfc-3172-11e7-8408-1c0ba3dbcf77.jpg)

Thanks again!

**Comment by JP-Ellis** [comment]
It works fine for me:

```latex
\RequirePackage{luatex85}
\documentclass[tikz, border=10pt]{standalone}

\usepackage[compat=1.1.0]{tikz-feynman}

\begin{document}
\feynmandiagram {
  v1 -- [double distance=1.5pt,edge label=$n$] e4[particle=$n$],
  v1 -- [double distance=1.5pt,edge label=$l$] e2[particle=$l$],
  e1 -- v1,
};

\feynmandiagram {
  v1 -- [double distance=1.5pt,edge label=$n$] e4[particle=$n$],
  v1 -- [double distance=1.5pt,edge label=$l$] e2[particle=$l$],
  e1 -- [opacity=0] v1,
};
\end{document}
```

![feng-1](https://cloud.githubusercontent.com/assets/3196162/25731291/5086e7da-3188-11e7-9b29-bcde2c4e6b04.png)
![feng-2](https://cloud.githubusercontent.com/assets/3196162/25731290/50867606-3188-11e7-8baa-73dfc5bb4493.png)

Your issue might be with your preamble.

**Comment by F-Feng** [comment]
Thanks so much, it works well now!
