### ISSUE TITLE
Charged particle arrow gets dashed border for scalars

### ISSUE THREAD

**Issue by martin-ueding** [JP-Ellis/tikz-feynman#4]
I created some diagram with uncharged scalars which had a loop. Since I need to label the loop momentum with a direction and the `momentum` key does not work with `semi-left` at the moment, I just used the `charged scalar` option to have an arrow tip along the path. This arrow tip inherits a dashed border from the path itself it seems:

![Dashed border around arrow](http://chaos.stw-bonn.de/users/mu/uploads/2015-11-17/charged-scalar.png)

That picture is taken from the documentation that I have downloaded, so it also occurs with your setup. It would be cool if you could prevent this dashed border somehow. This is not urgent in any way, I just wanted to tell you about this as it is visible if you look really close.

**Comment by JP-Ellis** [comment]
Thanks for the feedback.  I had noticed that and it has already been fixed on my working version.  I have a couple of issues remaining before I push the changes, but I'm hoping to release v1.0.0 (or at least a release candidate) in the next couple of days with a lot of cool changes :)

Unfortunately, the new release will break the current code, but with v1.0.0, the syntax should become stable.
