### ISSUE TITLE
Convenient way to draw a crossed diagram?

### ISSUE THREAD

**Issue by Turgon-Aran-Gondolin** [JP-Ellis/tikz-feynman#43]
Is there a convenient way to draw the following type of crossed diagrams without involving assigning positions directly to the vertexes as what you have done in your manual?
![image](https://user-images.githubusercontent.com/25204046/31305691-68a63216-ab05-11e7-826e-4bba2807910d.png)
Thanks a lot.

**Comment by JP-Ellis** [comment]
Unfortunately, Ti*k*Z-Feynman does not provide any algorithmic way of drawing such cross diagrams automatically as the algorithms will try and avoid producing such crossings as much as possible.

**Comment by Turgon-Aran-Gondolin** [comment]
Well, thanks anyway, I think I can stick with \diagram* for now.
