### ISSUE TITLE
Overlay a momentum arrow 

### ISSUE THREAD

**Issue by Turgon-Aran-Gondolin** [JP-Ellis/tikz-feynman#56]
Is there a way to manually overlay a momentum arrow upon a scalar line, for example? I understand that double fermion line might have to wait, but I'm wondering if there's a workaround like this?

**Comment by JP-Ellis** [comment]
I believe this is covered to some extent in the documentation?  If not, there are the keys `with arrow` and `with reversed arrow` which should work in conjunction with any other edge.

**Comment by Turgon-Aran-Gondolin** [comment]
Yes, I learned that in another issue already, that's why I closed this issue. However, I believe there's no such description in the documentation.
