### ISSUE TITLE
Export baseline value for an equation from Latex

### ISSUE THREAD

**Issue by rmurali84** [JP-Ellis/tikz-feynman#66]
Hi All,

I requested to use the latex equation into InDesing application as an Image (exp: eps or jpeg or PDF, etc.). Is there any options for exporting the baseline value from the latex file for the inline equation.

```
\documentclass{article}
\usepackage{amsmath}
\begin{document}
\begin{equation*}
F(x) &= \int^a_b \frac{1}{3}x^3
\end{equation*}
\end{document}
```

Thanks,
Murali

**Comment by JP-Ellis** [comment]
I unfortunately don't see quite how this relates to TikZ-Feynman, so I will be closing this.
