### ISSUE TITLE
Getting funky-looking diagrams using electron-positron scattering example

### ISSUE THREAD

**Issue by ghost-458** [JP-Ellis/tikz-feynman#76]
I'd like to start using tikz-feynman for my assignments but I'm having difficulty getting it working. I'm also new to TikZ and particle physics.
I'm running pgf verison 3.1.9a with tikz-feynman 1.1.0. I'm running on Windows 11 using pdflatex but it also looks weird on other compilers.

Here's the TeX that I'm using:
```latex
\documentclass{article}

\usepackage{tikz}
\usepackage[compat=1.1.0]{tikz-feynman}


\begin{document}
	\begin{tikzpicture}[baseline=(current  bounding  box.north west)]
		\begin{feynman}
			\feynmandiagram [horizontal=a to b] {
				i1 -- [fermion] a -- [fermion] i2,
				a -- [photon] b,
				f1 -- [fermion] b -- [fermion] f2,
			};
		\end{feynman}
	\end{tikzpicture}
\end{document}

```

and here's the output:

![image](https://user-images.githubusercontent.com/4730591/159531888-9b72c9cd-0cd2-4a1f-9418-8c131fc46c9d.png)

How do I get the expected output?

**Comment by ghost** [comment]
Nevermind! I tried lualatex again and it looks as-expected.

Edit: actually, it still fails when I compile my full homework assignment with lualatex, but it looks correct on the minimum working example. 🤔
