### ISSUE TITLE
\feynmandiagram does not work at all anymore in TexShop 4.73

### ISSUE THREAD

**Issue by avanishbsharma** [JP-Ellis/tikz-feynman#78]
The \feynmandiagram command does not work anymore in the newest TexShop version. E.g. the vanilla example 

`\feynmandiagram [horizontal=a to b] {
  i1 -- [fermion] a -- [fermion] i2,
  a -- [photon] b,
  f1 -- [fermion] b -- [fermion] f2,
};`

gives a weird diagram: 
<img width="463" alt="Schermafbeelding 2022-06-01 om 14 15 18" src="https://user-images.githubusercontent.com/66911928/171402313-d4579944-d430-435c-b751-a7c7b9cfe24c.png">

Please fix this.

Kind regards,

Avanish

**Comment by JP-Ellis** [comment]
Can you please check the log files and see if there are any errors and/or warnings?

This appears to be the same issue as [this question on StackOverflow](https://tex.stackexchange.com/questions/290599/error-when-using-tikz-feynman-package), can you confirm that the fix works for you?

**Comment by avanishbsharma** [comment]
Ahh yes, I need to compile with LuaLaTeX! Thanks, it works now. I indeed get errors which urge to compile with LuaLaTeX.
