### ISSUE TITLE
Momentum arrows unreadable

### ISSUE THREAD

**Issue by RobertSchuh** [JP-Ellis/tikz-feynman#80]
I tried reproducing the examples but when using

```
\feynmandiagram [large, vertical=e to f] {
  a -- [fermion] b -- [photon, momentum=\(k\)] c -- [fermion] d,
  b -- [fermion, momentum'=\(p_{1}\)] e -- [fermion, momentum'=\(p_{2}\)] c,
  e -- [gluon]  f,
  h -- [fermion] f -- [fermion] i;
};
```

I get:
![image](https://github.com/JP-Ellis/tikz-feynman/assets/53129059/6ee52aa8-bdcb-40e2-add5-9f613478954c)

How can I get readable momentum arrows?

**Comment by JP-Ellis** [comment]
Simply replace each `momentum` with `momentum'`. As per the documentation:

> The primed (`'`) version place the momentum arrow on the other side of the edge; that is, if the momentum arrow was on the right, it will be placed on the left of the edge
