### ISSUE TITLE
How to draw a line that connects the same point (single line loop)?

### ISSUE THREAD

**Issue by UlyssesZh** [JP-Ellis/tikz-feynman#81]
![image](https://github.com/JP-Ellis/tikz-feynman/assets/26196187/f4835e86-d842-4d28-aa4f-307884da80c6)

**Comment by JP-Ellis** [comment]
Closing this as:

1. GitHub is intended to report issues with TikZ-Feynman, not ask generic question.
2. No attempt at a solution is shown.

In the future, please direct these questions to the [LaTeX Stack Exchange](https://tex.stackexchange.com/), where you will most likely find your question answered already.
